INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('你好', 'ni3 hao3', 'Xin chào', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('再见', 'zai4 jian4', 'tạm biệt', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('谢谢', 'xie4 xie5', 'Cảm ơn', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('不客气', 'bu4 ke4 qi5', 'không có gì', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('对不起', 'dui4 bu4 qi3', 'Xin lỗi', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('没关系', 'mei2 guan1 xi5', 'Không sao đâu', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('早上好', 'zao3 shang4 hao3', 'Chào buổi sáng', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('晚上好', 'wan3 shang4 hao3', 'Chào buổi tối', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('晚安', 'wan3 an1', 'Chúc ngủ ngon', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('请', 'qing3', 'Xin vui lòng', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('爸爸', 'ba4 ba5', 'bố', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('妈妈', 'ma1 ma5', 'mẹ', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('哥哥', 'ge1 ge5', 'anh trai', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('弟弟', 'di4 di5', 'em trai', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('姐姐', 'jie3 jie5', 'chị gái', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('妹妹', 'mei4 mei5', 'em gái', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('爷爷', 'ye2 ye5', 'ông nội', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('奶奶', 'nai3 nai5', 'bà nội', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('儿子', 'er2 zi5', 'con trai', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('女儿', 'nv3 er2', 'con gái', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('丈夫', 'zhang4 fu5', 'chồng', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('妻子', 'qi1 zi5', 'vợ', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('家', 'jia1', 'trang chủ', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('家庭', 'jia1 ting2', 'gia đình', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('饭', 'fan4', 'cơm', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('面', 'mian4', 'mì', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('水', 'shui3', 'Nước', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('茶', 'cha2', 'trà', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('咖啡', 'ka1 fei1', 'cà phê', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('牛奶', 'niu2 nai3', 'sữa', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('面包', 'mian4 bao1', 'bánh mỳ', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('肉', 'rou4', 'thịt', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('鱼', 'yu2', 'cá', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('鸡', 'ji1', 'thịt gà', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蛋', 'dan4', 'trứng', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蔬菜', 'shu1 cai4', 'rau', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('水果', 'shui3 guo3', 'hoa quả', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('苹果', 'ping2 guo3', 'quả táo', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('香蕉', 'xiang1 jiao1', 'chuối', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('橙子', 'cheng2 zi5', 'quả cam', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('葡萄', 'pu2 tao2', 'quả nho', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('西瓜', 'xi1 gua1', 'dưa hấu', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('草莓', 'cao3 mei2', 'quả dâu', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('猫', 'mao1', 'con mèo', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('狗', 'gou3', 'chó', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('鸟', 'niao3', 'chim', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('马', 'ma3', 'ngựa', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('牛', 'niu2', 'con bò', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('猪', 'zhu1', 'con lợn', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('羊', 'yang2', 'con cừu', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('兔子', 'tu4 zi5', 'con thỏ', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('老虎', 'lao3 hu3', 'con hổ', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('狮子', 'shi1 zi5', 'con sư tử', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('大象', 'da4 xiang4', 'con voi', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('熊', 'xiong2', 'con gấu', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('猴子', 'hou2 zi5', 'con khỉ', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蛇', 'she2', 'rắn', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蝴蝶', 'hu2 die2', 'bươm bướm', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蜜蜂', 'mi4 feng1', 'con ong', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蚂蚁', 'ma3 yi3', 'kiến', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蜘蛛', 'zhi1 zhu1', 'nhện', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('红', 'hong2', 'màu đỏ', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('蓝', 'lan2', 'màu xanh da trời', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('绿', 'lv4', 'màu xanh lá', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('黄', 'huang2', 'màu vàng', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('黑', 'hei1', 'đen', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('白', 'bai2', 'trắng', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('紫', 'zi3', 'màu tím', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('粉', 'fen3', 'hồng', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('棕', 'zong1', 'màu nâu', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('灰', 'hui1', 'xám', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('银', 'yin2', 'bạc', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('金', 'jin1', 'vàng', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('太阳', 'tai4 yang2', 'mặt trời', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('月亮', 'yue4 liang4', 'mặt trăng', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('星星', 'xing1 xing5', 'ngôi sao', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('云', 'yun2', 'đám mây', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('雨', 'yu3', 'cơn mưa', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('雪', 'xue3', 'tuyết', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('风', 'feng1', 'gió', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('雷', 'lei2', 'sấm sét', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('闪电', 'shan3 dian4', 'tia sét', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('雾', 'wu4', 'sương mù', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('热', 're4', 'nóng', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('冷', 'leng3', 'lạnh lẽo', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('暖', 'nuan3', 'ấm', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('凉', 'liang2', 'mát mẻ', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('头', 'tou2', 'cái đầu', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('手', 'shou3', 'tay', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('脚', 'jiao3', 'chân', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('眼睛', 'yan3 jing1', 'mắt', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('鼻子', 'bi2 zi5', 'mũi', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('嘴', 'zui3', 'miệng', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('耳朵', 'er3 duo5', 'tai', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('头发', 'tou2 fa4', 'tóc', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('脸', 'lian3', 'khuôn mặt', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('脖子', 'bo2 zi5', 'cổ', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('肩膀', 'jian1 bang3', 'vai', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('胸', 'xiong1', 'ngực', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('背', 'bei4', 'mặt sau', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('胳膊', 'ge1 bo5', 'cánh tay', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('一', 'yi1', 'một', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('二', 'er4', 'hai', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('三', 'san1', 'ba', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('四', 'si4', 'bốn', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('五', 'wu3', 'năm', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('六', 'liu4', 'sáu', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('七', 'qi1', 'bảy', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('八', 'ba1', 'tám', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('九', 'jiu3', 'chín', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('十', 'shi2', 'mười', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('百', 'bai3', 'trăm', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('千', 'qian1', 'nghìn', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('万', 'wan4', 'mười nghìn', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('零', 'ling2', 'không', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('今天', 'jin1 tian1', 'Hôm nay', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('明天', 'ming2 tian1', 'Ngày mai', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('昨天', 'zuo2 tian1', 'Hôm qua', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('现在', 'xian4 zai4', 'Hiện nay', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('以前', 'yi3 qian2', 'trước', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('以后', 'yi3 hou4', 'sau đó', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('早上', 'zao3 shang4', 'buổi sáng', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('中午', 'zhong1 wu3', 'buổi trưa', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('下午', 'xia4 wu3', 'buổi chiều', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('晚上', 'wan3 shang4', 'buổi tối', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('月', 'yue4', 'tháng', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('日', 'ri4', 'ngày', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('分', 'fen1', 'phút', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('秒', 'miao3', 'thứ hai', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('学校', 'xue2 xiao4', 'trường học', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('医院', 'yi1 yuan4', 'bệnh viện', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('商店', 'shang1 dian4', 'cửa hàng', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('银行', 'yin2 hang2', 'ngân hàng', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('公园', 'gong1 yuan2', 'công viên', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('图书馆', 'tu2 shu1 guan3', 'thư viện', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('电影院', 'dian4 ying3 yuan4', 'rạp chiếu phim', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('餐厅', 'can1 ting1', 'nhà hàng', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('酒店', 'jiu3 dian4', 'khách sạn', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('机场', 'ji1 chang3', 'sân bay', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('车站', 'che1 zhan4', 'ga tàu', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('城市', 'cheng2 shi4', 'thành phố', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('国家', 'guo2 jia1', 'quốc gia', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('世界', 'shi4 jie4', 'thế giới', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('老师', 'lao3 shi1', 'giáo viên', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('医生', 'yi1 sheng1', 'bác sĩ', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('护士', 'hu4 shi4', 'y tá', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('警察', 'jing3 cha2', 'cảnh sát', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('司机', 'si1 ji1', 'tài xế', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('厨师', 'chu2 shi1', 'đầu bếp', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('工人', 'gong1 ren2', 'công nhân', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('农民', 'nong2 min2', 'nông dân', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('学生', 'xue2 sheng1', 'học sinh', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('老板', 'lao3 ban3', 'ông chủ', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('秘书', 'mi4 shu1', 'thư ký', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('工程师', 'gong1 cheng2 shi1', 'kỹ sư', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('律师', 'lv4 shi1', 'luật sư', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('记者', 'ji4 zhe3', 'nhà báo', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('艺术家', 'yi4 shu4 jia1', 'nghệ sĩ', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('书', 'shu1', 'sách', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('笔', 'bi3', 'cái bút', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('纸', 'zhi3', 'giấy', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('桌子', 'zhuo1 zi5', 'bàn', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('椅子', 'yi3 zi5', 'cái ghế', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('黑板', 'hei1 ban3', 'bảng đen', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('教室', 'jiao4 shi4', 'lớp học', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('办公室', 'ban4 gong1 shi4', 'văn phòng', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('实验室', 'shi2 yan4 shi4', 'phòng thí nghiệm', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('操场', 'cao1 chang3', 'sân chơi', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('食堂', 'shi2 tang2', 'quán ăn tự phục vụ', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('宿舍', 'su4 she4', 'ký túc xá', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('考试', 'kao3 shi4', 'bài thi', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('作业', 'zuo4 ye4', 'bài tập về nhà', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('课程', 'ke4 cheng2', 'khóa học', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('车', 'che1', 'xe hơi', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('公共汽车', 'gong1 gong4 qi4 che1', 'xe buýt', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('地铁', 'di4 tie3', 'tàu điện ngầm', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('火车', 'huo3 che1', 'xe lửa', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('飞机', 'fei1 ji1', 'máy bay', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('船', 'chuan2', 'tàu thủy', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('自行车', 'zi4 xing2 che1', 'xe đạp', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('摩托车', 'mo2 tuo1 che1', 'xe gắn máy', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('出租车', 'chu1 zu1 che1', 'Taxi', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('卡车', 'ka3 che1', 'xe tải', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('路', 'lu4', 'đường', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('桥', 'qiao2', 'cầu', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('红绿灯', 'hong2 lv4 deng1', 'đèn giao thông', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('停车', 'ting2 che1', 'bãi đậu xe', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('开车', 'kai1 che1', 'lái xe', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('钱', 'qian2', 'tiền bạc', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('买', 'mai3', 'mua', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('卖', 'mai4', 'bán', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('价格', 'jia4 ge2', 'giá', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('便宜', 'pian2 yi5', 'rẻ', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('贵', 'gui4', 'đắt', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('市场', 'shi4 chang3', 'chợ', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('超市', 'chao1 shi4', 'siêu thị', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('购物', 'gou4 wu4', 'mua sắm', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('付款', 'fu4 kuan3', 'sự chi trả', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('找钱', 'zhao3 qian2', 'thay đổi', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('信用卡', 'xin4 yong4 ka3', 'thẻ tín dụng', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('现金', 'xian4 jin1', 'tiền mặt', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('发票', 'fa1 piao4', 'biên lai', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('足球', 'zu2 qiu2', 'bóng đá', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('篮球', 'lan2 qiu2', 'bóng rổ', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('网球', 'wang3 qiu2', 'quần vợt', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('乒乓球', 'ping1 pang1 qiu2', 'bóng bàn', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('游泳', 'you2 yong3', 'bơi lội', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('跑步', 'pao3 bu4', 'đang chạy', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('骑自行车', 'qi2 zi4 xing2 che1', 'đạp xe', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('爬山', 'pa2 shan1', 'đi bộ đường dài', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('滑雪', 'hua3 xue3', 'trượt tuyết', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('滑冰', 'hua2 bing1', 'trượt băng', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('健身', 'jian4 shen1', 'sự thích hợp', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('瑜伽', 'yu2 jia1', 'yoga', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('拳击', 'quan2 ji1', 'quyền anh', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('武术', 'wu3 shu4', 'võ thuật', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('比赛', 'bi3 sai4', 'cuộc thi', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('高兴', 'gao1 xing4', 'vui mừng', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('难过', 'nan2 guo4', 'buồn', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('生气', 'sheng1 qi4', 'tức giận', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('害怕', 'hai4 pa4', 'sợ', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('惊讶', 'jing1 ya4', 'ngạc nhiên', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('担心', 'dan1 xin1', 'lo lắng', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('放松', 'fang4 song1', 'thư giãn', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('兴奋', 'xing1 fen4', 'hào hứng', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('累', 'lei4', 'mệt', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('困', 'kun4', 'buồn ngủ', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('饿', 'e4', 'đói bụng', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('渴', 'ke3', 'khát', '', NULL, 12, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('疼', 'teng2', 'nỗi đau', '', NULL, 13, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('舒服', 'shu1 fu5', 'thoải mái', '', NULL, 14, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('电脑', 'dian4 nao3', 'máy tính', '', NULL, 15, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('手机', 'shou3 ji1', 'điện thoại di động', '', NULL, 16, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('电视', 'dian4 shi4', 'tivi', '', NULL, 17, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('网络', 'wang3 luo4', 'internet', '', NULL, 1, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('网站', 'wang3 zhan4', 'trang web', '', NULL, 2, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('邮件', 'you2 jian4', 'e-mail', '', NULL, 3, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('软件', 'ruan3 jian4', 'phần mềm', '', NULL, 4, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('硬件', 'ying4 jian4', 'phần cứng', '', NULL, 5, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('数据', 'shu4 ju4', 'dữ liệu', '', NULL, 6, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('信息', 'xin4 xi1', 'thông tin', '', NULL, 7, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('程序', 'cheng2 xu4', 'chương trình', '', NULL, 8, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('游戏', 'you2 xi4', 'trò chơi', '', NULL, 9, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('视频', 'shi4 pin2', 'băng hình', '', NULL, 10, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('音频', 'yin1 pin2', 'âm thanh', '', NULL, 11, '');
INSERT INTO vocabulary (chinese_word, pinyin, meaning_vn, audio_url, lesson_id, category_id, part_of_speech) VALUES ('图片', 'tu2 pian4', 'hình ảnh', '', NULL, 12, '');